spring:
  application:
    name: eurekaserver

  config:
    import: "optional:configserver:http://localhost:8097/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true